spring.kafka.bootstrap-servers=localhost:9092

spring.datasource.url=jdbc:postgresql://localhost:5432/trading_platform
spring.datasource.username=admin
spring.datasource.password=password123

binance.websocket.url=wss://stream.binance.com:9443/ws/btcusdt@trade